[workspace]
resolver = "2"

members = [
    "libwinit",
    "libwinit30-builder",
]

exclude = [ "target" ]

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true

[profile.release]
opt-level = 3
